name: imgur_dart
description: A simple imgur API wrapper for Dart.
version: 0.0.4

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  sha_env:
    git: https://github.com/shalien/sha_env.git
